/**
 * Script to expand the word database with common daily-use words
 */

const fs = require('fs');
const path = require('path');

// Load existing words
const existingWordsPath = path.join(__dirname, '../data/sample-words.json');
const existingWords = JSON.parse(fs.readFileSync(existingWordsPath, 'utf8'));

// Create a set of existing words for quick lookup
const existingWordSet = new Set(existingWords.map(w => w.word.toLowerCase()));

// Common daily-use words organized by category
const newWords = [
  // Common verbs
  { word: "accept", freq: 85, category: "action", synonyms: ["agree", "approve", "receive"] },
  { word: "achieve", freq: 80, category: "action", synonyms: ["accomplish", "attain", "reach"] },
  { word: "acquire", freq: 75, category: "action", synonyms: ["obtain", "get", "gain"] },
  { word: "adapt", freq: 70, category: "action", synonyms: ["adjust", "modify", "change"] },
  { word: "address", freq: 85, category: "action", synonyms: ["handle", "deal", "tackle"] },
  { word: "advance", freq: 80, category: "action", synonyms: ["progress", "move", "proceed"] },
  { word: "analyze", freq: 90, category: "action", synonyms: ["examine", "study", "review"] },
  { word: "appear", freq: 95, category: "action", synonyms: ["show", "emerge", "surface"] },
  { word: "apply", freq: 90, category: "action", synonyms: ["use", "employ", "utilize"] },
  { word: "approach", freq: 85, category: "action", synonyms: ["method", "way", "technique"] },
  { word: "arrange", freq: 75, category: "action", synonyms: ["organize", "order", "plan"] },
  { word: "arrive", freq: 90, category: "action", synonyms: ["reach", "come", "get"] },
  { word: "assess", freq: 80, category: "action", synonyms: ["evaluate", "judge", "measure"] },
  { word: "assist", freq: 85, category: "action", synonyms: ["help", "aid", "support"] },
  { word: "assume", freq: 80, category: "action", synonyms: ["suppose", "presume", "believe"] },
  { word: "attach", freq: 75, category: "action", synonyms: ["connect", "join", "link"] },
  { word: "attempt", freq: 85, category: "action", synonyms: ["try", "effort", "endeavor"] },
  { word: "attend", freq: 80, category: "action", synonyms: ["go", "participate", "join"] },
  { word: "attract", freq: 75, category: "action", synonyms: ["draw", "appeal", "lure"] },
  { word: "avoid", freq: 85, category: "action", synonyms: ["prevent", "escape", "dodge"] },

  // Common nouns - everyday objects
  { word: "account", freq: 90, category: "business", synonyms: ["record", "report", "statement"] },
  { word: "activity", freq: 85, category: "general", synonyms: ["action", "task", "work"] },
  { word: "address", freq: 80, category: "location", synonyms: ["location", "place", "residence"] },
  { word: "advantage", freq: 75, category: "general", synonyms: ["benefit", "edge", "plus"] },
  { word: "advice", freq: 80, category: "general", synonyms: ["guidance", "suggestion", "tip"] },
  { word: "agreement", freq: 75, category: "business", synonyms: ["contract", "deal", "pact"] },
  { word: "amount", freq: 90, category: "general", synonyms: ["quantity", "sum", "total"] },
  { word: "answer", freq: 95, category: "general", synonyms: ["response", "reply", "solution"] },
  { word: "apartment", freq: 80, category: "location", synonyms: ["flat", "unit", "home"] },
  { word: "appearance", freq: 75, category: "general", synonyms: ["look", "aspect", "image"] },
  { word: "application", freq: 85, category: "technology", synonyms: ["app", "program", "software"] },
  { word: "appointment", freq: 80, category: "general", synonyms: ["meeting", "date", "session"] },
  { word: "approach", freq: 75, category: "general", synonyms: ["method", "way", "strategy"] },
  { word: "area", freq: 95, category: "location", synonyms: ["region", "zone", "space"] },
  { word: "argument", freq: 70, category: "general", synonyms: ["debate", "dispute", "discussion"] },
  { word: "article", freq: 85, category: "general", synonyms: ["item", "piece", "object"] },
  { word: "assignment", freq: 80, category: "education", synonyms: ["task", "project", "work"] },
  { word: "assistance", freq: 75, category: "general", synonyms: ["help", "aid", "support"] },
  { word: "association", freq: 70, category: "organization", synonyms: ["group", "society", "club"] },
  { word: "assumption", freq: 70, category: "general", synonyms: ["belief", "supposition", "idea"] },
  { word: "atmosphere", freq: 65, category: "environment", synonyms: ["mood", "feeling", "air"] },

  // Technology and modern life
  { word: "algorithm", freq: 70, category: "technology", synonyms: ["procedure", "method", "process"] },
  { word: "analytics", freq: 75, category: "technology", synonyms: ["analysis", "data", "metrics"] },
  { word: "artificial", freq: 70, category: "technology", synonyms: ["synthetic", "fake", "man-made"] },
  { word: "automation", freq: 65, category: "technology", synonyms: ["mechanization", "robotics"] },
  { word: "bandwidth", freq: 60, category: "technology", synonyms: ["capacity", "speed", "throughput"] },
  { word: "blockchain", freq: 55, category: "technology", synonyms: ["ledger", "chain", "crypto"] },
  { word: "browser", freq: 80, category: "technology", synonyms: ["navigator", "viewer", "client"] },
  { word: "cache", freq: 65, category: "technology", synonyms: ["storage", "buffer", "memory"] },
  { word: "cloud", freq: 85, category: "technology", synonyms: ["remote", "online", "virtual"] },
  { word: "cybersecurity", freq: 70, category: "technology", synonyms: ["security", "protection"] },
  { word: "dashboard", freq: 75, category: "technology", synonyms: ["panel", "interface", "display"] },
  { word: "deployment", freq: 70, category: "technology", synonyms: ["release", "launch", "rollout"] },
  { word: "digital", freq: 90, category: "technology", synonyms: ["electronic", "online", "virtual"] },
  { word: "download", freq: 85, category: "technology", synonyms: ["transfer", "get", "retrieve"] },
  { word: "encryption", freq: 65, category: "technology", synonyms: ["encoding", "security", "protection"] },
  { word: "framework", freq: 75, category: "technology", synonyms: ["structure", "platform", "foundation"] },
  { word: "interface", freq: 80, category: "technology", synonyms: ["connection", "link", "boundary"] },
  { word: "internet", freq: 95, category: "technology", synonyms: ["web", "net", "online"] },
  { word: "machine", freq: 85, category: "technology", synonyms: ["device", "equipment", "apparatus"] },
  { word: "network", freq: 90, category: "technology", synonyms: ["connection", "system", "grid"] },

  // Food and cooking
  { word: "breakfast", freq: 90, category: "food", synonyms: ["morning meal", "first meal"] },
  { word: "lunch", freq: 90, category: "food", synonyms: ["midday meal", "noon meal"] },
  { word: "dinner", freq: 90, category: "food", synonyms: ["evening meal", "supper"] },
  { word: "recipe", freq: 80, category: "food", synonyms: ["instructions", "formula", "method"] },
  { word: "ingredient", freq: 75, category: "food", synonyms: ["component", "element", "item"] },
  { word: "kitchen", freq: 85, category: "food", synonyms: ["cooking area", "galley"] },
  { word: "restaurant", freq: 85, category: "food", synonyms: ["eatery", "diner", "cafe"] },
  { word: "grocery", freq: 80, category: "food", synonyms: ["food store", "market", "supermarket"] },
  { word: "vegetable", freq: 80, category: "food", synonyms: ["veggie", "produce", "greens"] },
  { word: "fruit", freq: 85, category: "food", synonyms: ["produce", "fresh food"] },
  { word: "meat", freq: 80, category: "food", synonyms: ["protein", "flesh", "beef"] },
  { word: "chicken", freq: 85, category: "food", synonyms: ["poultry", "bird", "fowl"] },
  { word: "fish", freq: 80, category: "food", synonyms: ["seafood", "marine life"] },
  { word: "bread", freq: 85, category: "food", synonyms: ["loaf", "baked goods"] },
  { word: "cheese", freq: 80, category: "food", synonyms: ["dairy", "fromage"] },
  { word: "milk", freq: 85, category: "food", synonyms: ["dairy", "beverage"] },
  { word: "coffee", freq: 90, category: "food", synonyms: ["beverage", "drink", "java"] },
  { word: "tea", freq: 85, category: "food", synonyms: ["beverage", "drink", "brew"] },
  { word: "water", freq: 95, category: "food", synonyms: ["liquid", "beverage", "drink"] },
  { word: "juice", freq: 80, category: "food", synonyms: ["beverage", "drink", "liquid"] },

  // Transportation
  { word: "vehicle", freq: 85, category: "transportation", synonyms: ["car", "automobile", "transport"] },
  { word: "bicycle", freq: 75, category: "transportation", synonyms: ["bike", "cycle", "two-wheeler"] },
  { word: "motorcycle", freq: 70, category: "transportation", synonyms: ["bike", "motorbike"] },
  { word: "airplane", freq: 80, category: "transportation", synonyms: ["plane", "aircraft", "jet"] },
  { word: "train", freq: 80, category: "transportation", synonyms: ["railway", "locomotive"] },
  { word: "subway", freq: 75, category: "transportation", synonyms: ["metro", "underground", "tube"] },
  { word: "bus", freq: 85, category: "transportation", synonyms: ["coach", "transit"] },
  { word: "taxi", freq: 80, category: "transportation", synonyms: ["cab", "ride", "transport"] },
  { word: "traffic", freq: 85, category: "transportation", synonyms: ["congestion", "vehicles", "flow"] },
  { word: "parking", freq: 80, category: "transportation", synonyms: ["space", "lot", "garage"] },
  { word: "highway", freq: 75, category: "transportation", synonyms: ["freeway", "road", "interstate"] },
  { word: "street", freq: 90, category: "transportation", synonyms: ["road", "avenue", "lane"] },
  { word: "bridge", freq: 75, category: "transportation", synonyms: ["overpass", "crossing", "span"] },
  { word: "tunnel", freq: 70, category: "transportation", synonyms: ["passage", "underpass"] },
  { word: "station", freq: 80, category: "transportation", synonyms: ["stop", "terminal", "depot"] },
  { word: "airport", freq: 80, category: "transportation", synonyms: ["terminal", "airfield"] },
  { word: "ticket", freq: 85, category: "transportation", synonyms: ["pass", "fare", "admission"] },
  { word: "schedule", freq: 85, category: "transportation", synonyms: ["timetable", "agenda", "plan"] },
  { word: "destination", freq: 80, category: "transportation", synonyms: ["target", "goal", "endpoint"] },
  { word: "journey", freq: 75, category: "transportation", synonyms: ["trip", "travel", "voyage"] },

  // Health and body
  { word: "health", freq: 90, category: "health", synonyms: ["wellness", "fitness", "condition"] },
  { word: "doctor", freq: 85, category: "health", synonyms: ["physician", "medic", "practitioner"] },
  { word: "hospital", freq: 80, category: "health", synonyms: ["clinic", "medical center"] },
  { word: "medicine", freq: 80, category: "health", synonyms: ["medication", "drug", "treatment"] },
  { word: "exercise", freq: 85, category: "health", synonyms: ["workout", "fitness", "activity"] },
  { word: "nutrition", freq: 75, category: "health", synonyms: ["diet", "nourishment", "food"] },
  { word: "vitamin", freq: 70, category: "health", synonyms: ["supplement", "nutrient"] },
  { word: "symptom", freq: 75, category: "health", synonyms: ["sign", "indication", "manifestation"] },
  { word: "treatment", freq: 80, category: "health", synonyms: ["therapy", "care", "remedy"] },
  { word: "surgery", freq: 70, category: "health", synonyms: ["operation", "procedure"] },
  { word: "recovery", freq: 75, category: "health", synonyms: ["healing", "restoration", "improvement"] },
  { word: "prevention", freq: 75, category: "health", synonyms: ["protection", "avoidance"] },
  { word: "diagnosis", freq: 70, category: "health", synonyms: ["identification", "detection"] },
  { word: "therapy", freq: 75, category: "health", synonyms: ["treatment", "counseling", "care"] },
  { word: "wellness", freq: 70, category: "health", synonyms: ["health", "fitness", "wellbeing"] },
  { word: "fitness", freq: 80, category: "health", synonyms: ["health", "condition", "shape"] },
  { word: "mental", freq: 80, category: "health", synonyms: ["psychological", "emotional", "cognitive"] },
  { word: "physical", freq: 85, category: "health", synonyms: ["bodily", "corporeal", "material"] },
  { word: "emotional", freq: 75, category: "health", synonyms: ["feeling", "psychological", "mental"] },
  { word: "stress", freq: 85, category: "health", synonyms: ["pressure", "tension", "strain"] },

  // Education and learning
  { word: "education", freq: 85, category: "education", synonyms: ["learning", "schooling", "instruction"] },
  { word: "school", freq: 90, category: "education", synonyms: ["institution", "academy", "college"] },
  { word: "university", freq: 80, category: "education", synonyms: ["college", "institution", "academy"] },
  { word: "student", freq: 90, category: "education", synonyms: ["pupil", "learner", "scholar"] },
  { word: "teacher", freq: 85, category: "education", synonyms: ["instructor", "educator", "professor"] },
  { word: "lesson", freq: 80, category: "education", synonyms: ["class", "instruction", "tutorial"] },
  { word: "homework", freq: 75, category: "education", synonyms: ["assignment", "task", "work"] },
  { word: "textbook", freq: 70, category: "education", synonyms: ["book", "manual", "guide"] },
  { word: "library", freq: 80, category: "education", synonyms: ["collection", "archive", "repository"] },
  { word: "research", freq: 85, category: "education", synonyms: ["study", "investigation", "analysis"] },
  { word: "knowledge", freq: 85, category: "education", synonyms: ["information", "understanding", "wisdom"] },
  { word: "skill", freq: 85, category: "education", synonyms: ["ability", "talent", "expertise"] },
  { word: "learning", freq: 85, category: "education", synonyms: ["education", "study", "acquisition"] },
  { word: "training", freq: 80, category: "education", synonyms: ["instruction", "preparation", "coaching"] },
  { word: "course", freq: 80, category: "education", synonyms: ["class", "program", "curriculum"] },
  { word: "degree", freq: 75, category: "education", synonyms: ["qualification", "diploma", "certificate"] },
  { word: "graduation", freq: 70, category: "education", synonyms: ["completion", "finishing", "ceremony"] },
  { word: "scholarship", freq: 65, category: "education", synonyms: ["grant", "award", "funding"] },
  { word: "curriculum", freq: 70, category: "education", synonyms: ["program", "syllabus", "course"] },
  { word: "examination", freq: 75, category: "education", synonyms: ["test", "assessment", "evaluation"] },

  // Common daily words - Part 1
  { word: "beautiful", freq: 85, category: "adjective", synonyms: ["pretty", "attractive", "lovely"] },
  { word: "important", freq: 90, category: "adjective", synonyms: ["significant", "crucial", "vital"] },
  { word: "different", freq: 90, category: "adjective", synonyms: ["distinct", "unique", "various"] },
  { word: "available", freq: 85, category: "adjective", synonyms: ["accessible", "obtainable", "free"] },
  { word: "possible", freq: 90, category: "adjective", synonyms: ["feasible", "achievable", "potential"] },
  { word: "necessary", freq: 85, category: "adjective", synonyms: ["required", "essential", "needed"] },
  { word: "popular", freq: 80, category: "adjective", synonyms: ["well-liked", "favored", "trendy"] },
  { word: "special", freq: 85, category: "adjective", synonyms: ["unique", "particular", "distinctive"] },
  { word: "similar", freq: 80, category: "adjective", synonyms: ["alike", "comparable", "related"] },
  { word: "difficult", freq: 85, category: "adjective", synonyms: ["hard", "challenging", "tough"] },
  { word: "simple", freq: 85, category: "adjective", synonyms: ["easy", "basic", "straightforward"] },
  { word: "complex", freq: 75, category: "adjective", synonyms: ["complicated", "intricate", "involved"] },
  { word: "effective", freq: 80, category: "adjective", synonyms: ["successful", "efficient", "productive"] },
  { word: "efficient", freq: 75, category: "adjective", synonyms: ["effective", "productive", "streamlined"] },
  { word: "creative", freq: 80, category: "adjective", synonyms: ["innovative", "imaginative", "artistic"] },
  { word: "professional", freq: 85, category: "adjective", synonyms: ["expert", "skilled", "competent"] },
  { word: "personal", freq: 85, category: "adjective", synonyms: ["individual", "private", "own"] },
  { word: "social", freq: 80, category: "adjective", synonyms: ["communal", "public", "collective"] },
  { word: "natural", freq: 80, category: "adjective", synonyms: ["organic", "normal", "inherent"] },
  { word: "artificial", freq: 70, category: "adjective", synonyms: ["synthetic", "man-made", "fake"] },
  { word: "business", freq: 90, category: "business", synonyms: ["company", "enterprise", "organization"] },
  { word: "company", freq: 90, category: "business", synonyms: ["business", "corporation", "firm"] },
  { word: "office", freq: 85, category: "business", synonyms: ["workplace", "headquarters", "bureau"] },
  { word: "employee", freq: 85, category: "business", synonyms: ["worker", "staff", "personnel"] },
  { word: "manager", freq: 80, category: "business", synonyms: ["supervisor", "director", "boss"] },
  { word: "meeting", freq: 85, category: "business", synonyms: ["conference", "gathering", "session"] },
  { word: "project", freq: 85, category: "business", synonyms: ["task", "assignment", "initiative"] },
  { word: "deadline", freq: 80, category: "business", synonyms: ["due date", "time limit", "cutoff"] },
  { word: "budget", freq: 80, category: "business", synonyms: ["allocation", "funds", "resources"] },
  { word: "profit", freq: 75, category: "business", synonyms: ["earnings", "income", "revenue"] },
  { word: "customer", freq: 85, category: "business", synonyms: ["client", "buyer", "consumer"] },
  { word: "service", freq: 90, category: "business", synonyms: ["assistance", "support", "help"] },
  { word: "product", freq: 85, category: "business", synonyms: ["item", "goods", "merchandise"] },
  { word: "market", freq: 85, category: "business", synonyms: ["marketplace", "industry", "sector"] },
  { word: "strategy", freq: 80, category: "business", synonyms: ["plan", "approach", "method"] },
  { word: "goal", freq: 85, category: "business", synonyms: ["objective", "target", "aim"] },
  { word: "success", freq: 85, category: "business", synonyms: ["achievement", "accomplishment", "victory"] },
  { word: "failure", freq: 75, category: "business", synonyms: ["defeat", "setback", "disappointment"] },
  { word: "opportunity", freq: 80, category: "business", synonyms: ["chance", "possibility", "opening"] },
  { word: "challenge", freq: 80, category: "business", synonyms: ["difficulty", "obstacle", "problem"] },
  { word: "family", freq: 95, category: "family", synonyms: ["relatives", "household", "kin"] },
  { word: "parent", freq: 90, category: "family", synonyms: ["mother", "father", "guardian"] },
  { word: "child", freq: 90, category: "family", synonyms: ["kid", "offspring", "youngster"] },
  { word: "brother", freq: 85, category: "family", synonyms: ["sibling", "bro"] },
  { word: "sister", freq: 85, category: "family", synonyms: ["sibling", "sis"] },
  { word: "husband", freq: 80, category: "family", synonyms: ["spouse", "partner", "mate"] },
  { word: "wife", freq: 80, category: "family", synonyms: ["spouse", "partner", "mate"] },
  { word: "grandmother", freq: 75, category: "family", synonyms: ["grandma", "nana", "granny"] },
  { word: "grandfather", freq: 75, category: "family", synonyms: ["grandpa", "granddad"] },
  { word: "cousin", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "uncle", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "aunt", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "home", freq: 95, category: "location", synonyms: ["house", "residence", "dwelling"] },
  { word: "house", freq: 90, category: "location", synonyms: ["home", "residence", "building"] },
  { word: "room", freq: 85, category: "location", synonyms: ["chamber", "space", "area"] },
  { word: "bedroom", freq: 80, category: "location", synonyms: ["sleeping room", "chamber"] },
  { word: "bathroom", freq: 80, category: "location", synonyms: ["restroom", "washroom", "toilet"] },
  { word: "living", freq: 80, category: "location", synonyms: ["family room", "lounge", "parlor"] },
  { word: "garden", freq: 75, category: "location", synonyms: ["yard", "backyard", "lawn"] },
  { word: "today", freq: 95, category: "time", synonyms: ["now", "present", "current day"] },
  { word: "tomorrow", freq: 90, category: "time", synonyms: ["next day", "following day"] },
  { word: "yesterday", freq: 90, category: "time", synonyms: ["previous day", "last day"] },
  { word: "morning", freq: 90, category: "time", synonyms: ["dawn", "early day", "am"] },
  { word: "afternoon", freq: 85, category: "time", synonyms: ["midday", "pm"] },
  { word: "evening", freq: 85, category: "time", synonyms: ["night", "dusk", "twilight"] },
  { word: "night", freq: 90, category: "time", synonyms: ["evening", "darkness", "nighttime"] },
  { word: "weekend", freq: 85, category: "time", synonyms: ["saturday sunday", "days off"] },
  { word: "holiday", freq: 80, category: "time", synonyms: ["vacation", "break", "celebration"] },
  { word: "birthday", freq: 80, category: "time", synonyms: ["anniversary", "celebration"] },
  { word: "season", freq: 75, category: "time", synonyms: ["period", "time of year"] },
  { word: "spring", freq: 75, category: "time", synonyms: ["springtime", "season"] },
  { word: "summer", freq: 75, category: "time", synonyms: ["summertime", "season"] },
  { word: "autumn", freq: 70, category: "time", synonyms: ["fall", "season"] },
  { word: "winter", freq: 75, category: "time", synonyms: ["wintertime", "season"] },
  { word: "january", freq: 70, category: "time", synonyms: ["month", "new year"] },
  { word: "february", freq: 70, category: "time", synonyms: ["month"] },
  { word: "march", freq: 70, category: "time", synonyms: ["month"] },
  { word: "april", freq: 70, category: "time", synonyms: ["month"] },
  { word: "may", freq: 70, category: "time", synonyms: ["month"] },
  { word: "june", freq: 70, category: "time", synonyms: ["month"] },
  { word: "july", freq: 70, category: "time", synonyms: ["month"] },
  { word: "august", freq: 70, category: "time", synonyms: ["month"] },
  { word: "september", freq: 70, category: "time", synonyms: ["month"] },
  { word: "october", freq: 70, category: "time", synonyms: ["month"] },
  { word: "november", freq: 70, category: "time", synonyms: ["month"] },
  { word: "december", freq: 70, category: "time", synonyms: ["month"] },
  { word: "color", freq: 80, category: "general", synonyms: ["hue", "shade", "tint"] },
  { word: "red", freq: 85, category: "color", synonyms: ["crimson", "scarlet", "cherry"] },
  { word: "blue", freq: 85, category: "color", synonyms: ["azure", "navy", "cobalt"] },
  { word: "green", freq: 85, category: "color", synonyms: ["emerald", "lime", "forest"] },
  { word: "yellow", freq: 80, category: "color", synonyms: ["golden", "amber", "lemon"] },
  { word: "orange", freq: 80, category: "color", synonyms: ["tangerine", "peach", "coral"] },
  { word: "purple", freq: 75, category: "color", synonyms: ["violet", "lavender", "plum"] },
  { word: "pink", freq: 75, category: "color", synonyms: ["rose", "magenta", "fuchsia"] },
  { word: "brown", freq: 75, category: "color", synonyms: ["tan", "chocolate", "coffee"] },
  { word: "black", freq: 85, category: "color", synonyms: ["dark", "ebony", "charcoal"] },
  { word: "white", freq: 85, category: "color", synonyms: ["ivory", "snow", "pearl"] },
  { word: "gray", freq: 80, category: "color", synonyms: ["grey", "silver", "ash"] }
];,

  // Common adjectives
  { word: "beautiful", freq: 85, category: "adjective", synonyms: ["pretty", "attractive", "lovely"] },
  { word: "important", freq: 90, category: "adjective", synonyms: ["significant", "crucial", "vital"] },
  { word: "different", freq: 90, category: "adjective", synonyms: ["distinct", "unique", "various"] },
  { word: "available", freq: 85, category: "adjective", synonyms: ["accessible", "obtainable", "free"] },
  { word: "possible", freq: 90, category: "adjective", synonyms: ["feasible", "achievable", "potential"] },
  { word: "necessary", freq: 85, category: "adjective", synonyms: ["required", "essential", "needed"] },
  { word: "popular", freq: 80, category: "adjective", synonyms: ["well-liked", "favored", "trendy"] },
  { word: "special", freq: 85, category: "adjective", synonyms: ["unique", "particular", "distinctive"] },
  { word: "similar", freq: 80, category: "adjective", synonyms: ["alike", "comparable", "related"] },
  { word: "difficult", freq: 85, category: "adjective", synonyms: ["hard", "challenging", "tough"] },
  { word: "simple", freq: 85, category: "adjective", synonyms: ["easy", "basic", "straightforward"] },
  { word: "complex", freq: 75, category: "adjective", synonyms: ["complicated", "intricate", "involved"] },
  { word: "effective", freq: 80, category: "adjective", synonyms: ["successful", "efficient", "productive"] },
  { word: "efficient", freq: 75, category: "adjective", synonyms: ["effective", "productive", "streamlined"] },
  { word: "creative", freq: 80, category: "adjective", synonyms: ["innovative", "imaginative", "artistic"] },
  { word: "professional", freq: 85, category: "adjective", synonyms: ["expert", "skilled", "competent"] },
  { word: "personal", freq: 85, category: "adjective", synonyms: ["individual", "private", "own"] },
  { word: "social", freq: 80, category: "adjective", synonyms: ["communal", "public", "collective"] },
  { word: "natural", freq: 80, category: "adjective", synonyms: ["organic", "normal", "inherent"] },
  { word: "artificial", freq: 70, category: "adjective", synonyms: ["synthetic", "man-made", "fake"] },

  // Business and work
  { word: "business", freq: 90, category: "business", synonyms: ["company", "enterprise", "organization"] },
  { word: "company", freq: 90, category: "business", synonyms: ["business", "corporation", "firm"] },
  { word: "office", freq: 85, category: "business", synonyms: ["workplace", "headquarters", "bureau"] },
  { word: "employee", freq: 85, category: "business", synonyms: ["worker", "staff", "personnel"] },
  { word: "manager", freq: 80, category: "business", synonyms: ["supervisor", "director", "boss"] },
  { word: "meeting", freq: 85, category: "business", synonyms: ["conference", "gathering", "session"] },
  { word: "project", freq: 85, category: "business", synonyms: ["task", "assignment", "initiative"] },
  { word: "deadline", freq: 80, category: "business", synonyms: ["due date", "time limit", "cutoff"] },
  { word: "budget", freq: 80, category: "business", synonyms: ["allocation", "funds", "resources"] },
  { word: "profit", freq: 75, category: "business", synonyms: ["earnings", "income", "revenue"] },
  { word: "customer", freq: 85, category: "business", synonyms: ["client", "buyer", "consumer"] },
  { word: "service", freq: 90, category: "business", synonyms: ["assistance", "support", "help"] },
  { word: "product", freq: 85, category: "business", synonyms: ["item", "goods", "merchandise"] },
  { word: "market", freq: 85, category: "business", synonyms: ["marketplace", "industry", "sector"] },
  { word: "strategy", freq: 80, category: "business", synonyms: ["plan", "approach", "method"] },
  { word: "goal", freq: 85, category: "business", synonyms: ["objective", "target", "aim"] },
  { word: "success", freq: 85, category: "business", synonyms: ["achievement", "accomplishment", "victory"] },
  { word: "failure", freq: 75, category: "business", synonyms: ["defeat", "setback", "disappointment"] },
  { word: "opportunity", freq: 80, category: "business", synonyms: ["chance", "possibility", "opening"] },
  { word: "challenge", freq: 80, category: "business", synonyms: ["difficulty", "obstacle", "problem"] },

  // Home and family
  { word: "family", freq: 95, category: "family", synonyms: ["relatives", "household", "kin"] },
  { word: "parent", freq: 90, category: "family", synonyms: ["mother", "father", "guardian"] },
  { word: "child", freq: 90, category: "family", synonyms: ["kid", "offspring", "youngster"] },
  { word: "brother", freq: 85, category: "family", synonyms: ["sibling", "bro"] },
  { word: "sister", freq: 85, category: "family", synonyms: ["sibling", "sis"] },
  { word: "husband", freq: 80, category: "family", synonyms: ["spouse", "partner", "mate"] },
  { word: "wife", freq: 80, category: "family", synonyms: ["spouse", "partner", "mate"] },
  { word: "grandmother", freq: 75, category: "family", synonyms: ["grandma", "nana", "granny"] },
  { word: "grandfather", freq: 75, category: "family", synonyms: ["grandpa", "granddad"] },
  { word: "cousin", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "uncle", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "aunt", freq: 70, category: "family", synonyms: ["relative", "family member"] },
  { word: "home", freq: 95, category: "location", synonyms: ["house", "residence", "dwelling"] },
  { word: "house", freq: 90, category: "location", synonyms: ["home", "residence", "building"] },
  { word: "room", freq: 85, category: "location", synonyms: ["chamber", "space", "area"] },
  { word: "bedroom", freq: 80, category: "location", synonyms: ["sleeping room", "chamber"] },
  { word: "bathroom", freq: 80, category: "location", synonyms: ["restroom", "washroom", "toilet"] },
  { word: "kitchen", freq: 85, category: "location", synonyms: ["cooking area", "galley"] },
  { word: "living", freq: 80, category: "location", synonyms: ["family room", "lounge", "parlor"] },
  { word: "garden", freq: 75, category: "location", synonyms: ["yard", "backyard", "lawn"] },

  // Time and dates
  { word: "today", freq: 95, category: "time", synonyms: ["now", "present", "current day"] },
  { word: "tomorrow", freq: 90, category: "time", synonyms: ["next day", "following day"] },
  { word: "yesterday", freq: 90, category: "time", synonyms: ["previous day", "last day"] },
  { word: "morning", freq: 90, category: "time", synonyms: ["dawn", "early day", "am"] },
  { word: "afternoon", freq: 85, category: "time", synonyms: ["midday", "pm"] },
  { word: "evening", freq: 85, category: "time", synonyms: ["night", "dusk", "twilight"] },
  { word: "night", freq: 90, category: "time", synonyms: ["evening", "darkness", "nighttime"] },
  { word: "weekend", freq: 85, category: "time", synonyms: ["saturday sunday", "days off"] },
  { word: "holiday", freq: 80, category: "time", synonyms: ["vacation", "break", "celebration"] },
  { word: "birthday", freq: 80, category: "time", synonyms: ["anniversary", "celebration"] },
  { word: "anniversary", freq: 70, category: "time", synonyms: ["celebration", "commemoration"] },
  { word: "season", freq: 75, category: "time", synonyms: ["period", "time of year"] },
  { word: "spring", freq: 75, category: "time", synonyms: ["springtime", "season"] },
  { word: "summer", freq: 75, category: "time", synonyms: ["summertime", "season"] },
  { word: "autumn", freq: 70, category: "time", synonyms: ["fall", "season"] },
  { word: "winter", freq: 75, category: "time", synonyms: ["wintertime", "season"] },
  { word: "january", freq: 70, category: "time", synonyms: ["month", "new year"] },
  { word: "february", freq: 70, category: "time", synonyms: ["month"] },
  { word: "march", freq: 70, category: "time", synonyms: ["month"] },
  { word: "april", freq: 70, category: "time", synonyms: ["month"] },
  { word: "may", freq: 70, category: "time", synonyms: ["month"] },
  { word: "june", freq: 70, category: "time", synonyms: ["month"] },
  { word: "july", freq: 70, category: "time", synonyms: ["month"] },
  { word: "august", freq: 70, category: "time", synonyms: ["month"] },
  { word: "september", freq: 70, category: "time", synonyms: ["month"] },
  { word: "october", freq: 70, category: "time", synonyms: ["month"] },
  { word: "november", freq: 70, category: "time", synonyms: ["month"] },
  { word: "december", freq: 70, category: "time", synonyms: ["month"] },

  // Colors
  { word: "color", freq: 80, category: "general", synonyms: ["hue", "shade", "tint"] },
  { word: "red", freq: 85, category: "color", synonyms: ["crimson", "scarlet", "cherry"] },
  { word: "blue", freq: 85, category: "color", synonyms: ["azure", "navy", "cobalt"] },
  { word: "green", freq: 85, category: "color", synonyms: ["emerald", "lime", "forest"] },
  { word: "yellow", freq: 80, category: "color", synonyms: ["golden", "amber", "lemon"] },
  { word: "orange", freq: 80, category: "color", synonyms: ["tangerine", "peach", "coral"] },
  { word: "purple", freq: 75, category: "color", synonyms: ["violet", "lavender", "plum"] },
  { word: "pink", freq: 75, category: "color", synonyms: ["rose", "magenta", "fuchsia"] },
  { word: "brown", freq: 75, category: "color", synonyms: ["tan", "chocolate", "coffee"] },
  { word: "black", freq: 85, category: "color", synonyms: ["dark", "ebony", "charcoal"] },
  { word: "white", freq: 85, category: "color", synonyms: ["ivory", "snow", "pearl"] },
  { word: "gray", freq: 80, category: "color", synonyms: ["grey", "silver", "ash"] },

  // Numbers and quantities
  { word: "number", freq: 85, category: "general", synonyms: ["digit", "figure", "numeral"] },
  { word: "first", freq: 90, category: "general", synonyms: ["initial", "primary", "beginning"] },
  { word: "second", freq: 85, category: "general", synonyms: ["next", "following", "subsequent"] },
  { word: "third", freq: 80, category: "general", synonyms: ["final", "last", "ultimate"] },
  { word: "last", freq: 85, category: "general", synonyms: ["final", "ultimate", "end"] },
  { word: "next", freq: 90, category: "general", synonyms: ["following", "subsequent", "coming"] },
  { word: "previous", freq: 75, category: "general", synonyms: ["prior", "earlier", "former"] },
  { word: "many", freq: 90, category: "general", synonyms: ["numerous", "several", "multiple"] },
  { word: "few", freq: 85, category: "general", synonyms: ["some", "several", "limited"] },
  { word: "all", freq: 95, category: "general", synonyms: ["everything", "entire", "whole"] },
  { word: "none", freq: 80, category: "general", synonyms: ["nothing", "zero", "nil"] },
  { word: "some", freq: 90, category: "general", synonyms: ["several", "few", "certain"] },
  { word: "most", freq: 85, category: "general", synonyms: ["majority", "nearly all", "bulk"] },
  { word: "every", freq: 85, category: "general", synonyms: ["each", "all", "any"] },
  { word: "each", freq: 85, category: "general", synonyms: ["every", "individual", "respective"] },
  { word: "other", freq: 90, category: "general", synonyms: ["different", "alternative", "another"] },
  { word: "another", freq: 85, category: "general", synonyms: ["other", "additional", "further"] },
  { word: "both", freq: 80, category: "general", synonyms: ["two", "pair", "couple"] },
  { word: "either", freq: 75, category: "general", synonyms: ["one or other", "any"] },
  { word: "neither", freq: 70, category: "general", synonyms: ["not either", "none"] }
];
];

// Filter out words that already exist
const wordsToAdd = newWords.filter(word => !existingWordSet.has(word.word.toLowerCase()));

console.log(`Found ${wordsToAdd.length} new words to add`);
console.log(`Current word count: ${existingWords.length}`);
console.log(`New total will be: ${existingWords.length + wordsToAdd.length}`);

// Combine existing and new words
const allWords = [...existingWords, ...wordsToAdd];

// Write back to file
fs.writeFileSync(existingWordsPath, JSON.stringify(allWords, null, 2));

console.log(`✅ Successfully added ${wordsToAdd.length} new words!`);
console.log(`📊 Total words now: ${allWords.length}`);
